### ISSUE TITLE
Make scraper module

### ISSUE THREAD

**Issue by harryandriyan** [harryandriyan/21scrap#1]
make scraper module to get list of city from https://m.21cineplex.com/gui.list_city.php?sid= and save it to json

**Comment by adam2809** [comment]
Alright let me handle it

**Comment by Kaushal-Mittal** [comment]
All materials and **contents (text, graphics, and every attributes)** of 21Cineplex or 21Cineplex.com website are copyrights and trademarks of 21Cineplex. No part of this website may be reproduced in any form without our written permission. **Misuse of the entire content or any part, multiply, translate, use, or utilize it without written permission from 21Cineplex will be subject to criminal and / or civil penalties.**

**Comment by baltazarix** [comment]
@harryandriyan, you accept PRs according to the rule "first come first served" or you respect nabbing like @adam2809 did?

**Comment by harryandriyan** [comment]
I'm sorry @adam2809 , it's has been done by #2 
@baltazarix "first come first served" , thanks

**Comment by adam2809** [comment]
Yeah sorry guys got kinda confused by the first e-mail:

All materials and contents (text, graphics, and every attributes) of
21Cineplex or 21Cineplex.com website are copyrights and trademarks of
21Cineplex. No part of this website may be reproduced in any form without
our written permission. Misuse of the entire content or any part, multiply,
translate, use, or utilize it without written permission from 21Cineplex
will be subject to criminal and / or civil penalties.

I mean if they don't want their website scraped than I won't.




śr., 10 paź 2018 o 05:26 Harry Andriyan <notifications@github.com>
napisał(a):
